# Generated by Django 5.1 on 2024-08-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_alter_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('qa', 'QA')], max_length=20),
        ),
    ]
